from django.db import models

class EventInfo(models.Model):
	title = models.TextField()
	description = models.TextField()
	cost = models.TextField()
	timeStart = models.DateTimeField()
	timeStop = models.DateTimeField()
	venue = models.TextField()
	venueAddress = models.TextField()
	location = models.TextField()
	latitude = models.CharField(max_length=20)
	longitude = models.CharField(max_length=20)
	eventImage = models.TextField()
	bookings = models.TextField()
	category = models.TextField()
	weblink = models.TextField()
	age = models.TextField()
	meetingPoint = models.TextField()
	requirements = models.TextField()
	showType = models.TextField()
	schedule = models.TextField()
	outdoors = models.BooleanField()