# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('cost', models.TextField()),
                ('timeStart', models.DateTimeField()),
                ('timeStop', models.DateTimeField()),
                ('venue', models.TextField()),
                ('venueAddress', models.TextField()),
                ('location', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('eventImage', models.TextField()),
                ('bookings', models.TextField()),
                ('category', models.TextField()),
                ('weblink', models.TextField()),
                ('age', models.TextField()),
                ('meetingPoint', models.TextField()),
                ('requirements', models.TextField()),
                ('showType', models.TextField()),
                ('schedule', models.TextField()),
                ('outdoors', models.BooleanField()),
            ],
        ),
    ]
