# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='timeStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='timeStop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
