# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160730_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=main.models.text_default)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='location',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='imageURL',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='age',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='bookings',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='category',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='cost',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='description',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='eventImage',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='meetingPoint',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='requirements',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='schedule',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='showType',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='title',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='venue',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='venueAddress',
            field=models.TextField(default=main.models.text_default),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='weblink',
            field=models.TextField(default=main.models.text_default),
        ),
    ]
