# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160730_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='imageURL',
        ),
    ]
