# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_eventinfo_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='longitude',
        ),
    ]
